### PR TITLE
Config with default template

### PR DESCRIPTION
**Pull request by gforcada**
@ericof I know you worked on the `plone/code-analysis-action` but if you ask me to run `plone/meta` on it, then it makes no sense to install `pre-commit` to instead use something else to run the QA tools 😅 

Tomorrow we do a pillow fight about it 😆

### CODE REVIEW

**Comment by ericof** [comment]
@gforcada The idea is to use only plone/meta (and I'm willing to give up on the code-analysis-tool as long as the solution also works for things in the collective organization)

I noticed .editorconfig on plone/meta is a bit limited, so I will try to add other file extensions there before I approve and merge this PR)

**Comment by ericof** [comment]
@gforcada Could we update this again? 😅

**Comment by gforcada** [comment]
Sure, no problem, I've been polishing `plone/meta` and `mr.roboto` so we can mass update all core packages with all the cool new checks we have been adding as of late. Next will be collective, yes 🚀

**Comment by gforcada** [comment]
Obsoleted by #26

**Pull request closed without merging**
